export const BIKE_WHATSAPP_NUMBER = '5492617042980';

export const getBikeWhatsAppLink = (message = '') => {
  const encoded = encodeURIComponent(message || "Hi! I found you through Bike Match Lessons and I'd like to book an MTB lesson.");
  return `https://wa.me/${BIKE_WHATSAPP_NUMBER}?text=${encoded}`;
};

export const BIKE_RESORTS = [
  // USA
  { id: 1,  name: 'Moab',                   location: 'Utah, USA',                region: 'usa',          instructors: 22, difficulty: 'All Levels',    rating: 5.0, trailType: 'Enduro / XC',        image: 'https://images.unsplash.com/photo-1527359443443-84a48aec73d2?w=600&q=80' },
  { id: 2,  name: 'Park City Trails',        location: 'Utah, USA',                region: 'usa',          instructors: 18, difficulty: 'All Levels',    rating: 4.9, trailType: 'All-Mountain / XC',  image: 'https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=600&q=80' },
  { id: 3,  name: 'Snowbird Summer',         location: 'Utah, USA',                region: 'usa',          instructors: 16, difficulty: 'Advanced',      rating: 4.8, trailType: 'Downhill / Enduro',  image: 'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=600&q=80' },
  { id: 4,  name: 'Brian Head Trails',       location: 'Utah, USA',                region: 'usa',          instructors: 10, difficulty: 'All Levels',    rating: 4.6, trailType: 'XC / All-Mountain',  image: 'https://images.unsplash.com/photo-1502904550040-7534597429ae?w=600&q=80' },
  { id: 5,  name: 'Crested Butte',           location: 'Colorado, USA',            region: 'usa',          instructors: 20, difficulty: 'All Levels',    rating: 4.9, trailType: 'All-Mountain / XC',  image: 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=600&q=80' },
  { id: 6,  name: 'Durango Trails',          location: 'Colorado, USA',            region: 'usa',          instructors: 14, difficulty: 'Intermediate+', rating: 4.8, trailType: 'XC / Enduro',        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80' },
  { id: 7,  name: 'Keystone Bike Park',      location: 'Colorado, USA',            region: 'usa',          instructors: 18, difficulty: 'All Levels',    rating: 4.7, trailType: 'Downhill / Park',    image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03d?w=600&q=80' },
  { id: 8,  name: 'Aspen Summer Trails',     location: 'Colorado, USA',            region: 'usa',          instructors: 22, difficulty: 'All Levels',    rating: 5.0, trailType: 'All-Mountain / XC',  image: 'https://images.unsplash.com/photo-1476611338391-6f395a0dd82e?w=600&q=80' },
  { id: 9,  name: 'Mammoth Bike Park',       location: 'California, USA',          region: 'usa',          instructors: 20, difficulty: 'All Levels',    rating: 4.8, trailType: 'Downhill / Enduro',  image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=600&q=80' },
  { id: 10, name: 'Big Bear Bike Park',      location: 'California, USA',          region: 'usa',          instructors: 12, difficulty: 'All Levels',    rating: 4.6, trailType: 'Downhill / XC',      image: 'https://images.unsplash.com/photo-1499744937866-d7e566a20a61?w=600&q=80' },
  { id: 11, name: 'Lake Tahoe Flume Trail',  location: 'California/Nevada, USA',   region: 'usa',          instructors: 14, difficulty: 'Intermediate+', rating: 4.9, trailType: 'XC / All-Mountain',  image: 'https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=600&q=80' },
  // Europe
  { id: 12, name: 'Grandvalira Bike Park',   location: 'Andorra',                  region: 'europe',       instructors: 12, difficulty: 'All Levels',    rating: 4.7, trailType: 'All-Mountain / XC',  image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80' },
  { id: 13, name: 'Baqueira Summer',         location: 'Lleida, Spain',            region: 'europe',       instructors: 10, difficulty: 'All Levels',    rating: 4.7, trailType: 'XC / Enduro',        image: 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=600&q=80' },
  // South America
  { id: 14, name: 'Portillo Summer',         location: 'Los Andes, Chile',         region: 'southamerica', instructors: 10, difficulty: 'Intermediate+', rating: 4.8, trailType: 'Enduro / All-Mountain',image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80' },
  { id: 15, name: 'Cerro Catedral Trails',   location: 'Bariloche, Argentina',     region: 'southamerica', instructors: 14, difficulty: 'All Levels',    rating: 4.9, trailType: 'All-Mountain / XC',  image: 'https://images.unsplash.com/photo-1527359443443-84a48aec73d2?w=600&q=80' },
  { id: 16, name: 'Mendoza Mountain Bike',   location: 'Mendoza, Argentina',       region: 'southamerica', instructors: 10, difficulty: 'All Levels',    rating: 4.7, trailType: 'XC / Enduro',        image: 'https://images.unsplash.com/photo-1502904550040-7534597429ae?w=600&q=80' },
  // Other
  { id: 17, name: 'Whistler Bike Park',      location: 'British Columbia, Canada', region: 'other',        instructors: 35, difficulty: 'All Levels',    rating: 5.0, trailType: 'Downhill / Enduro',  image: 'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=600&q=80' },
  { id: 18, name: 'Niseko Trails',           location: 'Hokkaido, Japan',          region: 'other',        instructors: 12, difficulty: 'All Levels',    rating: 4.8, trailType: 'XC / All-Mountain',  image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03d?w=600&q=80' },
];

export const BIKE_INSTRUCTORS = [
  { id: 1, name: 'Felipe Montoya',   avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80', certifications: ['PMBI Level 3', 'EWS Pro'], specialties: ['Downhill', 'Enduro', 'Advanced'], languages: ['EN', 'ES'], resorts: ['Moab', 'Whistler Bike Park'], rating: 4.9, reviews: 287 },
  { id: 2, name: 'Zoe Thompson',     avatar: 'https://images.unsplash.com/photo-1494790108755-2616b2e5a7b8?w=200&q=80', certifications: ['PMBI Level 2', 'XC Specialist'], specialties: ['XC', 'All-Mountain', 'Beginners'], languages: ['EN'], resorts: ['Park City Trails', 'Lake Tahoe Flume Trail'], rating: 5.0, reviews: 412 },
  { id: 3, name: 'Santiago Vega',    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80', certifications: ['PMBI Level 3', 'Enduro Coach'], specialties: ['Enduro', 'Technical Terrain', 'Pump Track'], languages: ['EN', 'ES', 'FR'], resorts: ['Cerro Catedral Trails', 'Portillo Summer'], rating: 4.8, reviews: 203 },
  { id: 4, name: 'Emma Wilson',      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80', certifications: ['PMBI Level 2', 'Kids MTB Specialist'], specialties: ['Beginners', 'Kids', 'All-Mountain'], languages: ['EN'], resorts: ['Mammoth Bike Park', 'Big Bear Bike Park'], rating: 4.9, reviews: 318 },
  { id: 5, name: 'Matías Guerrero',  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80', certifications: ['PMBI Level 3', 'Downhill Pro'], specialties: ['Downhill', 'Park', 'Freestyle'], languages: ['ES', 'EN'], resorts: ['Keystone Bike Park', 'Crested Butte'], rating: 4.8, reviews: 176 },
  { id: 6, name: 'Lucas Moreau',     avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&q=80', certifications: ['PMBI Level 2', 'Trail Guide'], specialties: ['XC', 'Trail', 'Enduro'], languages: ['FR', 'EN', 'ES'], resorts: ['Grandvalira Bike Park', 'Baqueira Summer'], rating: 4.7, reviews: 141 },
];

export const BIKE_TESTIMONIALS = [
  { id: 1, name: 'Marco Jiménez',    country: 'Mexico',    avatar: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=100&q=80', rating: 5, text: 'Felipe me llevó a bajar un trail negro en Moab que nunca hubiera intentado solo. En dos días aprendí más que en un año de práctica. ¡Brutal!', instructor: 'Felipe Montoya', type: 'Advanced', resort: 'Moab' },
  { id: 2, name: 'Claire Dubois',    country: 'France',    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=100&q=80', rating: 5, text: 'Zoe turned me from a nervous trail rider into someone who actually charges rock gardens. Her patience and technique are world-class.', instructor: 'Zoe Thompson', type: 'Intermediate', resort: 'Park City Trails' },
  { id: 3, name: 'Diego Ramírez',    country: 'Argentina', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80', rating: 5, text: 'Santiago conoce cada rincón de Bariloche en MTB. La clase de técnica en terreno técnico fue increíble. Bike Match es lo mejor que existe.', instructor: 'Santiago Vega', type: 'Advanced', resort: 'Cerro Catedral Trails' },
  { id: 4, name: 'Sophie Miller',    country: 'USA',       avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80', rating: 5, text: 'My 8-year-old went from scared of trails to ripping berms in one day with Emma. She has a gift for teaching kids. Absolutely incredible.', instructor: 'Emma Wilson', type: 'Kids', resort: 'Mammoth Bike Park' },
  { id: 5, name: 'Tomás Herrera',    country: 'Chile',     avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80', rating: 5, text: 'Matías es un crack total. Aprendí a saltar tabletops correctamente y a dominar el pump track. Ahora entiendo por qué el MTB es adicción.', instructor: 'Matías Guerrero', type: 'Intermediate', resort: 'Keystone Bike Park' },
  { id: 6, name: 'James O\'Brien',   country: 'UK',        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80', rating: 5, text: 'Lucas showed me trails in Andorra I\'d have never found alone. His enduro coaching is precise and fun. Best day on a bike ever, full stop.', instructor: 'Lucas Moreau', type: 'Intermediate', resort: 'Grandvalira Bike Park' },
];

export const BIKE_FAQS = [
  {
    q_en: 'Do I need my own mountain bike?',
    q_es: '¿Necesito bicicleta de montaña propia?',
    a_en: 'Not necessarily! Many resorts offer high-quality rental MTBs, and our instructors can help you choose the right size and type for your lesson. If you do own a bike, bring it — riding familiar equipment always helps.',
    a_es: '¡No necesariamente! Muchos resorts ofrecen alquiler de bicicletas de montaña de alta calidad, y nuestros instructores pueden ayudarte a elegir el tamaño y tipo correcto para tu clase. Si tenés bicicleta propia, traela — siempre ayuda sentirse cómodo con el equipo.',
  },
  {
    q_en: 'What protective gear do I need?',
    q_es: '¿Qué equipo de protección necesito?',
    a_en: 'A full-face or trail helmet is mandatory. We also strongly recommend knee pads, elbow pads, gloves, and eye protection. For downhill lessons, a full-face helmet and body armor are required. Most bike parks rent protective gear on-site.',
    a_es: 'Un casco integral o de trail es obligatorio. También recomendamos fuertemente rodilleras, coderas, guantes y protección ocular. Para clases de downhill, se requiere casco integral y protecciones corporales. La mayoría de los bike parks alquila equipo de protección en sitio.',
  },
  {
    q_en: 'What is the minimum age for MTB lessons?',
    q_es: '¿Cuál es la edad mínima para las clases de MTB?',
    a_en: 'We accept riders from 5 years old with our specially trained kids instructors. There is no maximum age — mountain biking is for life! Adult beginners are always welcome.',
    a_es: 'Aceptamos riders desde los 5 años con nuestros instructores especializados en niños. ¡No hay edad máxima! Los principiantes adultos siempre son bienvenidos.',
  },
  {
    q_en: 'Do you teach downhill and enduro?',
    q_es: '¿Enseñan downhill y enduro?',
    a_en: 'Absolutely! Our advanced instructors are certified for downhill, enduro, all-mountain, XC, and pump track disciplines. Tell us your goal and we\'ll match you with the right specialist.',
    a_es: '¡Por supuesto! Nuestros instructores avanzados están certificados en downhill, enduro, all-mountain, XC y pump track. Contanos tu objetivo y te hacemos match con el especialista correcto.',
  },
  {
    q_en: 'Can I choose my instructor?',
    q_es: '¿Puedo elegir a mi instructor?',
    a_en: 'Yes! We match you based on your riding level, discipline preference, language, and location. You can also browse instructor profiles and request a specific one. Your progression is our priority.',
    a_es: '¡Sí! Te emparejamos según tu nivel de riding, disciplina preferida, idioma y ubicación. También podés ver los perfiles de instructores y solicitar uno específico. Tu progresión es nuestra prioridad.',
  },
  {
    q_en: 'Are there guided trail tours?',
    q_es: '¿Hay tours guiados de senderos?',
    a_en: 'Yes! Beyond single lessons, we offer guided trail experiences where our instructors take you through the best local trails while coaching your technique along the way. Multi-day adventure packages are also available — contact us via WhatsApp for details.',
    a_es: '¡Sí! Más allá de las clases individuales, ofrecemos experiencias de trail guiadas donde nuestros instructores te llevan por los mejores senderos locales mientras entrenan tu técnica en el camino. También hay paquetes de aventura de varios días — contactanos por WhatsApp para más detalles.',
  },
  {
    q_en: 'What is included in an MTB lesson?',
    q_es: '¿Qué incluye una clase de MTB?',
    a_en: 'Each lesson includes a certified instructor, personalized coaching for your level and goals, trail selection matched to your skills, real-time feedback, and a progress debrief. Bike and gear rental are not included but we help arrange them.',
    a_es: 'Cada clase incluye un instructor certificado, coaching personalizado para tu nivel y objetivos, selección de senderos adaptados a tus habilidades, retroalimentación en tiempo real y un resumen de progreso. El alquiler de bicicleta y equipo no está incluido, pero te ayudamos a gestionarlo.',
  },
  {
    q_en: 'Do you have Spanish-speaking instructors?',
    q_es: '¿Tienen instructores que hablen español?',
    a_en: 'Yes! Several of our instructors are native Spanish speakers, and our whole team is bilingual. Just let us know your language preference when booking.',
    a_es: '¡Sí! Varios de nuestros instructores son hispanohablantes nativos y todo nuestro equipo es bilingüe. Solo indicanos tu preferencia de idioma al reservar.',
  },
];

export const BIKE_BLOG_POSTS = [
  {
    id: 1,
    category: 'Tips', category_es: 'Consejos',
    date: 'Jan 10, 2025',
    title_en: '10 MTB Skills Every Beginner Must Learn',
    title_es: '10 Habilidades de MTB que Todo Principiante Debe Aprender',
    excerpt_en: 'From body position to braking technique — the fundamentals that separate confident trail riders from white-knuckled beginners.',
    excerpt_es: 'Desde la posición corporal hasta la técnica de frenado — los fundamentos que separan a los riders seguros de los principiantes tensos.',
    content_en: 'Mountain biking has a steep initial learning curve, but mastering the basics transforms the experience completely.\n\n**1. Neutral position.** Stand off the saddle with knees and elbows slightly bent, weight centered. This is your attack position — everything else builds from here.\n\n**2. Look ahead, not down.** Your bike goes where your eyes go. Train yourself to look 10–15 feet ahead of your front wheel.\n\n**3. Brake before, not during, corners.** Scrub speed on the straight, then release the brakes as you lean into the turn. Braking mid-corner causes skids and crashes.\n\n**4. Two-finger braking.** Use only your index and middle finger on the levers. This keeps a firm grip on the bar with the remaining fingers.\n\n**5. Weight the outside pedal.** In corners, drop your outside pedal to 6 o\'clock and push through it. This lowers your center of gravity and adds grip.\n\n**6. Pump the terrain.** Use dips and rollers to generate speed without pedaling. Push down through troughs and pull up over crests.\n\n**7. Stay relaxed.** Tension in your arms transfers every bump to your body. Bend those elbows and let the bike move beneath you.\n\n**8. Progressive braking.** Squeeze gradually, don\'t grab. Front brake provides 70% of stopping power but can pitch you over the bars if grabbed hard.\n\n**9. Choose your line.** Always plan 2–3 seconds ahead. Pick smooth lines around rocks and roots, not over them — at first.\n\n**10. Get coaching early.** One session with a certified instructor is worth months of trial and error. Bad habits formed early take years to undo.',
    content_es: 'El mountain bike tiene una curva de aprendizaje inicial empinada, pero dominar los fundamentos transforma completamente la experiencia.\n\n**1. Posición neutra.** Pararte fuera del sillín con rodillas y codos ligeramente flexionados, peso centrado. Esta es tu posición de ataque — todo lo demás se construye desde aquí.\n\n**2. Mirar adelante, no abajo.** Tu bicicleta va hacia donde van tus ojos. Entrenar para mirar 3–5 metros adelante de tu rueda delantera.\n\n**3. Frenar antes, no durante, las curvas.** Reducí velocidad en la recta, luego soltá los frenos al inclinarte en el giro. Frenar en medio de una curva causa derrapes y caídas.\n\n**4. Frenado de dos dedos.** Usá solo el índice y el medio en las palancas. Esto mantiene un agarre firme en el manubrio con los dedos restantes.\n\n**5. Cargar el pedal exterior.** En las curvas, bajá el pedal exterior a las 6 en punto y empujá a través de él. Esto baja tu centro de gravedad y agrega tracción.\n\n**6. Bombear el terreno.** Usá bajadas y rodillos para generar velocidad sin pedalear. Empujá hacia abajo en los valles y tirá hacia arriba en las crestas.\n\n**7. Mantenete relajado.** La tensión en los brazos transfiere cada golpe a tu cuerpo. Doblá esos codos y dejá que la bicicleta se mueva debajo de vos.\n\n**8. Frenado progresivo.** Apretá gradualmente, no agarrés de golpe. El freno delantero provee el 70% de la potencia de frenado pero puede tirarte si lo apretás fuerte.\n\n**9. Elegí tu línea.** Siempre planificá 2–3 segundos adelante. Elegí líneas suaves alrededor de rocas y raíces, no sobre ellas — al principio.\n\n**10. Conseguí coaching temprano.** Una sesión con un instructor certificado vale meses de prueba y error. Los malos hábitos formados temprano llevan años deshacerlos.',
    image: 'https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=600&q=80',
    author: 'Zoe Thompson',
  },
  {
    id: 2,
    category: 'Technique', category_es: 'Técnica',
    date: 'Jan 25, 2025',
    title_en: 'Downhill Technique: How to Ride Technical Terrain',
    title_es: 'Técnica Downhill: Cómo Rodar en Terreno Técnico',
    excerpt_en: 'Rock gardens, roots, drops — technical downhill terrain doesn\'t have to be scary. Here\'s how to approach it with confidence.',
    excerpt_es: 'Jardines de rocas, raíces, drops — el terreno técnico de downhill no tiene que dar miedo. Así es cómo abordarlo con confianza.',
    content_en: 'Technical terrain is where mountain biking gets both terrifying and addictive. The key is breaking it down into manageable challenges.\n\n**Body position for steep terrain.** As the gradient steepens, shift your weight back — hips behind the saddle, arms extended. Think of keeping your body parallel to the slope, not the bike.\n\n**Rock gardens.** The instinct is to brake through rocks. The reality: pick up speed before the rocks, stay loose, let the bike bounce. Momentum is your friend. Choose a line 3–4 meters ahead and commit.\n\n**Roots.** Hit them straight when possible. At angles, the front wheel can deflect and wash out. Keep your weight back and let the bike bounce over them.\n\n**Drops.** Small drops (under 60cm) are all about commitment. Roll to the edge in attack position, spot your landing, let the front wheel drop naturally, compress your legs on landing. Hesitating is the main cause of nose-diving.\n\n**Cornering on steep descents.** Use the full width of the trail. Enter wide, apex tight, exit wide. Lean the bike more than your body. Look through the corner to the exit.\n\n**Managing fear.** It\'s normal. Walk features until you\'re comfortable visualizing the line. Mental rehearsal works. A certified coach can give you progressions — small wins that build genuine confidence.',
    content_es: 'El terreno técnico es donde el mountain bike se vuelve tanto aterrador como adictivo. La clave es dividirlo en desafíos manejables.\n\n**Posición corporal en terreno empinado.** A medida que el gradiente se empina, desplazá tu peso hacia atrás — caderas detrás del sillín, brazos extendidos. Pensá en mantener tu cuerpo paralelo a la pendiente, no a la bicicleta.\n\n**Jardines de rocas.** El instinto es frenar entre las rocas. La realidad: agarrá velocidad antes de las rocas, mantenete suelto, dejá que la bicicleta rebote. El momentum es tu amigo. Elegí una línea 3–4 metros adelante y comprometete.\n\n**Raíces.** Golpealas en línea recta cuando sea posible. En ángulos, la rueda delantera puede desviarse y resbalarse. Manté tu peso atrás y dejá que la bicicleta rebote sobre ellas.\n\n**Drops.** Los drops pequeños (menos de 60cm) son todo sobre el compromiso. Rodá al borde en posición de ataque, ubicá tu aterrizaje, dejá que la rueda delantera caiga naturalmente, comprimí las piernas al aterrizar. La duda es la principal causa de caerse de cabeza.\n\n**Virajes en descensos empinados.** Usá el ancho completo del sendero. Entrá ancho, vértice apretado, salí ancho. Incliná más la bicicleta que tu cuerpo. Mirá a través de la curva hacia la salida.\n\n**Manejando el miedo.** Es normal. Caminá las secciones hasta que te sientas cómodo visualizando la línea. El ensayo mental funciona. Un coach certificado puede darte progresiones — pequeños logros que construyen confianza genuina.',
    image: 'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=600&q=80',
    author: 'Felipe Montoya',
  },
  {
    id: 3,
    category: 'Destinations', category_es: 'Destinos',
    date: 'Feb 8, 2025',
    title_en: 'Best MTB Destinations 2025: Where to Ride',
    title_es: 'Mejores Destinos MTB 2025: Dónde Rodar',
    excerpt_en: 'From Moab\'s red rock to Whistler\'s legendary downhill — the definitive guide to the world\'s top mountain biking destinations.',
    excerpt_es: 'Desde las rocas rojas de Moab hasta el legendario downhill de Whistler — la guía definitiva de los mejores destinos de mountain bike del mundo.',
    content_en: 'The world\'s best MTB destinations offer more than just trails — they offer complete riding ecosystems.\n\n**Moab, Utah — The Crown Jewel**\nSlickrock Trail is the most famous MTB trail in the world for a reason — its unique sandstone surface grips tires unlike anything else. But Moab is much more than Slickrock: Porcupine Rim, the Whole Enchilada, and Captain Ahab all deliver world-class experiences at different skill levels. Best season: March–May, September–November.\n\n**Whistler Bike Park, Canada**\nThe largest bike park in the world. Over 80 marked trails from beginner-friendly to some of the most technical downhill runs on earth. The A-Line and Dirt Merchant are bucket-list descents. Whistler\'s infrastructure for riders is unmatched — bike schools, demo centers, lift-accessed terrain.\n\n**Crested Butte, Colorado**\n401 Trail is widely considered the best XC trail in Colorado. Combined with trails like Doctor Park and the 403, Crested Butte delivers epic singletrack through wildflower meadows and aspen groves. Authentic, not over-developed, incredibly beautiful.\n\n**Bariloche, Argentina — South America\'s Crown**\nCerro Catedral\'s trails offer high alpine riding with breathtaking Patagonian views. The lift-accessed downhill combined with cross-country routes through native forest makes this one of the most unique riding experiences in the world. Season: December–April.\n\n**Andorra — Europe\'s Hidden Gem**\nGrandvalira\'s bike park offers 40km of marked trails including downhill runs used for World Cup competition. Combine it with Andorra\'s tax-free shopping and you have the perfect European riding trip.',
    content_es: 'Los mejores destinos MTB del mundo ofrecen más que senderos — ofrecen ecosistemas de riding completos.\n\n**Moab, Utah — La Joya de la Corona**\nSlickrock Trail es el sendero MTB más famoso del mundo por algo — su única superficie de piedra arenisca agarra los neumáticos como ningún otro lugar. Pero Moab es mucho más que Slickrock: Porcupine Rim, the Whole Enchilada y Captain Ahab ofrecen experiencias de primer nivel a diferentes niveles de habilidad. Mejor temporada: marzo–mayo, septiembre–noviembre.\n\n**Whistler Bike Park, Canadá**\nEl bike park más grande del mundo. Más de 80 senderos marcados desde aptos para principiantes hasta algunas de las bajadas de downhill más técnicas de la tierra. A-Line y Dirt Merchant son descensos de lista de deseos. La infraestructura de Whistler para riders es incomparable — escuelas de bike, centros de demo, terreno accesible por telecabina.\n\n**Crested Butte, Colorado**\nEl sendero 401 es ampliamente considerado el mejor trail de XC en Colorado. Combinado con senderos como Doctor Park y el 403, Crested Butte entrega épico singletrack a través de praderas de flores silvestres y bosques de álamos. Auténtico, no sobre-desarrollado, increíblemente hermoso.\n\n**Bariloche, Argentina — La Corona de Sudamérica**\nLos senderos del Cerro Catedral ofrecen riding alpino con impresionantes vistas patagónicas. El downhill accesible por telecabina combinado con rutas de cross-country a través de bosque nativo hace de esto una de las experiencias de riding más únicas del mundo. Temporada: diciembre–abril.',
    image: 'https://images.unsplash.com/photo-1527359443443-84a48aec73d2?w=600&q=80',
    author: 'Santiago Vega',
  },
  {
    id: 4,
    category: 'Safety', category_es: 'Seguridad',
    date: 'Feb 20, 2025',
    title_en: 'MTB Safety: Protect Yourself on the Trail',
    title_es: 'Seguridad MTB: Protegete en el Sendero',
    excerpt_en: 'Mountain biking is an extreme sport. Understanding trail etiquette, proper gear, and emergency protocols keeps you riding for years.',
    excerpt_es: 'El mountain bike es un deporte extremo. Conocer el etiquette del sendero, el equipo correcto y los protocolos de emergencia te mantiene rodando por años.',
    content_en: 'Crashes are part of mountain biking. Serious injuries don\'t have to be.\n\n**Gear up properly.** Helmet (full-face for DH, trail helmet for XC/AM), knee pads, elbow pads, gloves, protective eyewear. Don\'t cut corners on protection — the cost of a hospital visit vastly exceeds quality gear.\n\n**Know the trail rating system.** Green (easy), Blue (intermediate), Black (advanced), Double Black (expert). Ride within your ability level. Progression is earned, not rushed.\n\n**Trail etiquette.** Uphill riders have right of way on most trails (except designated downhill-only). Announce yourself when overtaking ("on your left"). Yield to hikers and horses. Never skid unnecessarily — it damages trails.\n\n**Ride with a buddy.** Especially on remote trails, never ride alone. If you must ride solo, tell someone your route and expected return time. Carry a basic first-aid kit.\n\n**Pre-ride bike check.** The ABC: Air (tire pressure), Brakes (test both levers), Chain (lubed and moving smoothly). Also check quick releases, headset, and saddle clamp.\n\n**Carry emergency supplies.** Tube, CO2 or pump, tire levers, multi-tool, emergency blanket, charged phone (downloaded offline map). Remote trails may have no cell signal.\n\n**Weather and trail conditions.** Wet roots and rocks are dramatically more slippery. Be conservative in wet conditions. Know where the trail exits are in case of sudden weather changes.',
    content_es: 'Las caídas son parte del mountain bike. Las lesiones graves no tienen que serlo.\n\n**Equipáte correctamente.** Casco (integral para DH, trail para XC/AM), rodilleras, coderas, guantes, protección ocular. No escatimes en protección — el costo de una visita al hospital supera con creces el equipo de calidad.\n\n**Conocé el sistema de clasificación de senderos.** Verde (fácil), Azul (intermedio), Negro (avanzado), Doble Negro (experto). Rodá dentro de tu nivel. La progresión se gana, no se apresura.\n\n**Etiquette del sendero.** Los riders que suben tienen derecho de paso en la mayoría de senderos (excepto los designados solo de bajada). Anunciarte al adelantar ("a tu izquierda"). Ceder el paso a senderistas y caballos. Nunca derrapar innecesariamente — daña los senderos.\n\n**Rodá con un compañero.** Especialmente en senderos remotos, nunca rodés solo. Si debés rodar solo, decile a alguien tu ruta y hora de retorno esperada. Llevá un botiquín básico de primeros auxilios.\n\n**Revisión pre-ride.** El ABC: Aire (presión de neumáticos), Frenos (probá ambas palancas), Cadena (lubricada y moviéndose bien). También revisá cierres rápidos, dirección y abrazadera del sillín.\n\n**Llevá suministros de emergencia.** Tubo, CO2 o bomba, palancas de neumáticos, multiherramienta, manta de emergencia, teléfono cargado (con mapa offline descargado). Los senderos remotos pueden no tener señal de celular.',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    author: 'Emma Wilson',
  },
  {
    id: 5,
    category: 'Tips', category_es: 'Consejos',
    date: 'Mar 5, 2025',
    title_en: 'MTB Gear Guide: What You Actually Need',
    title_es: 'Guía de Equipo MTB: Lo que Realmente Necesitás',
    excerpt_en: 'The MTB gear market is overwhelming. Here\'s what genuinely makes a difference vs. what\'s marketing hype.',
    excerpt_es: 'El mercado de equipo MTB es abrumador. Esto es lo que genuinamente marca la diferencia vs. lo que es marketing.',
    content_en: 'You don\'t need to spend a fortune to ride well. But some gear investments pay massive dividends.\n\n**The Bike — Rent First, Buy Smart**\nFor beginners, rent for 5–10 days before buying. Key categories:\n- *Hardtail:* Front suspension only, lighter and cheaper, great for XC and smooth trails.\n- *Full-suspension:* Front and rear suspension, more control on technical terrain, more expensive.\n- *Wheel size:* 29" rolls over obstacles better (XC/trail), 27.5" is more nimble (enduro/DH), 27.5+ has wider tires for more traction.\n\n**The Helmet — Don\'t Compromise**\nFor trail/all-mountain: A certified MIPS trail helmet. For downhill: Full-face is non-negotiable. Spend $150–300+ on a helmet. Your brain is worth it.\n\n**Suspension Setup**\nMost riders have their suspension set too soft or too hard. Start with sag: 25–30% for XC, 30–35% for trail/enduro. A bike shop or instructor can set this in 10 minutes and transform how your bike rides.\n\n**Tires — The Biggest Bang for Buck**\nUpgrading tires makes a bigger difference than most component upgrades. Match tread pattern to terrain (knobby for loose/wet, semi-slick for hardpack). Tubeless setup eliminates most flats and allows lower pressures.\n\n**Pedals and Shoes**\nFlat pedals with grippy pins + flat shoes: More forgiving for beginners, easy to bail. Clipless pedals + MTB shoes: More efficiency, better connection, learning curve to disengage.',
    content_es: 'No necesitás gastar una fortuna para rodar bien. Pero algunas inversiones en equipo dan dividendos masivos.\n\n**La Bicicleta — Alquilá Primero, Comprá Inteligente**\nPara principiantes, alquilá 5–10 días antes de comprar. Categorías clave:\n- *Hardtail:* Solo suspensión delantera, más liviana y económica, excelente para XC y senderos suaves.\n- *Full-suspension:* Suspensión delantera y trasera, más control en terreno técnico, más cara.\n- *Tamaño de rueda:* 29" rueda mejor sobre obstáculos (XC/trail), 27.5" es más ágil (enduro/DH), 27.5+ tiene neumáticos más anchos para más tracción.\n\n**El Casco — Sin Compromisos**\nPara trail/all-mountain: Un casco trail certificado con MIPS. Para downhill: El integral es innegociable. Gastá $150–300+ en un casco. Tu cerebro lo vale.\n\n**Configuración de Suspensión**\nLa mayoría de los riders tienen la suspensión configurada muy blanda o muy dura. Empezá con el sag: 25–30% para XC, 30–35% para trail/enduro. Una tienda de bicicletas o instructor puede configurarlo en 10 minutos y transformar cómo anda tu bicicleta.\n\n**Neumáticos — El Mayor Retorno por Inversión**\nActualizar los neumáticos hace más diferencia que la mayoría de los upgrades de componentes. Adaptá el dibujo al terreno (con tacos para suelto/húmedo, semi-liso para compacto). La configuración tubeless elimina la mayoría de los pinchazos y permite presiones más bajas.',
    image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03d?w=600&q=80',
    author: 'Matías Guerrero',
  },
  {
    id: 6,
    category: 'Technique', category_es: 'Técnica',
    date: 'Mar 18, 2025',
    title_en: 'How to Choose Your Perfect MTB Trail Destination',
    title_es: 'Cómo Elegir tu Destino MTB Perfecto',
    excerpt_en: 'Not all trail systems are created equal. Match a destination to your riding style, level, and travel preferences for the ultimate MTB trip.',
    excerpt_es: 'No todos los sistemas de senderos son iguales. Matcheá un destino con tu estilo de riding, nivel y preferencias de viaje para el viaje MTB perfecto.',
    content_en: 'The right destination amplifies your riding. The wrong one can be frustrating, dangerous, or just boring.\n\n**Assess the trail network first.** Look at total trail kilometers, difficulty breakdown, and trail types (XC, enduro, downhill, freeride). A beginner needs a resort with 40%+ green/blue trails. An advanced rider wants technical blacks and lift access.\n\n**Consider the trail surface.** Moab\'s sandstone is unlike anything else on earth. Whistler\'s loamy soil and berms feel completely different. Rocky Mountain granite, Andorran limestone — surface matters for technique and tire choice.\n\n**Lift access vs. pedal up.** Downhill parks (Whistler, Keystone, Mammoth Bike Park) give you way more runs per day but are lift-fee dependent. Cross-country destinations require earning your descents. Both are valid — know which you prefer.\n\n**Season and weather.** Most mountain destinations have a 4–6 month riding season. Moab is a spring/fall destination. Whistler peaks in summer. Bariloche is December–April. Check shoulder seasons for fewer crowds and lower prices.\n\n**Trip planning for couples/families.** Not everyone in your group rides? Choose destinations with non-riding activities (hiking, dining, culture). Whistler, Aspen, and Bariloche are full-experience destinations. Remote trails work if everyone is committed to riding.\n\n**Book an instructor for the first day.** Even experienced riders benefit from a local guide who knows every line, the best beginner-friendly routes, and the hidden gems the trail map doesn\'t show.',
    content_es: 'El destino correcto amplifica tu riding. El equivocado puede ser frustrante, peligroso o simplemente aburrido.\n\n**Evaluá la red de senderos primero.** Mirá los kilómetros totales de sendero, el desglose de dificultad y los tipos de sendero (XC, enduro, downhill, freeride). Un principiante necesita un resort con 40%+ de senderos verdes/azules. Un rider avanzado quiere negros técnicos y acceso por telecabina.\n\n**Considerá la superficie del sendero.** La piedra arenisca de Moab es como ningún otro lugar del mundo. El suelo franco de Whistler y sus berms se sienten completamente diferentes. El granito de las Montañas Rocosas, la caliza andorrana — la superficie importa para la técnica y la elección de neumáticos.\n\n**Acceso por telecabina vs. pedalear.** Los parques de downhill (Whistler, Keystone, Mammoth Bike Park) te dan muchas más bajadas por día pero dependen de la tarifa del lift. Los destinos de cross-country requieren ganarte los descensos. Ambos son válidos — conocé cuál preferís.\n\n**Temporada y clima.** La mayoría de los destinos de montaña tienen una temporada de 4–6 meses. Moab es un destino de primavera/otoño. Whistler tiene su pico en verano. Bariloche es de diciembre a abril. Revisá las temporadas bajas para menos multitudes y precios más bajos.',
    image: 'https://images.unsplash.com/photo-1502904550040-7534597429ae?w=600&q=80',
    author: 'Lucas Moreau',
  },
];

export const BIKE_PRICING = [
  {
    id: 'single',
    title_en: 'Single MTB Class',
    title_es: 'Por Clase MTB',
    subtitle_en: 'Perfect for a one-day experience',
    subtitle_es: 'Perfecto para una experiencia de un día',
    price_usd: 140,
    duration_en: '90 minutes',
    duration_es: '90 minutos',
    features_en: ['Certified MTB instructor', 'Trail selection for your level', 'Technique coaching & feedback', 'Cancel 48h before (no penalty)'],
    features_es: ['Instructor MTB certificado', 'Selección de senderos a tu nivel', 'Coaching de técnica y retroalimentación', 'Cancelación 48h antes sin penalidad'],
    cta_en: 'Book a Single Class',
    cta_es: 'Reservar Clase Suelta',
    highlight: false,
    badge: null,
  },
  {
    id: 'pack5',
    title_en: '5-Class MTB Package',
    title_es: 'Paquete 5 Clases MTB',
    subtitle_en: 'Most popular for real progression',
    subtitle_es: 'La más popular para progresar de verdad',
    price_usd: 625,
    original_usd: 700,
    duration_en: '90 min each · Valid 1 week',
    duration_es: '90 min c/u · Validez 1 semana',
    features_en: ['Dedicated instructor', 'Progressive trail progression', 'Video feedback session', 'Flexible scheduling'],
    features_es: ['Instructor dedicado', 'Progresión de senderos progresiva', 'Sesión de feedback en video', 'Horarios flexibles'],
    cta_en: 'Get 5 Classes',
    cta_es: 'Comenzar con 5 Clases',
    highlight: true,
    badge_en: 'SAVE 10%',
    badge_es: 'AHORRO 10%',
  },
  {
    id: 'pack10',
    title_en: '10-Class MTB Package',
    title_es: 'Paquete 10 Clases MTB',
    subtitle_en: 'Total transformation guaranteed',
    subtitle_es: 'Transformación total garantizada',
    price_usd: 1100,
    original_usd: 1400,
    duration_en: '90 min each · Valid 30 days',
    duration_es: '90 min c/u · Validez 30 días',
    features_en: ['Dedicated instructor + skill assessments', 'Personalized progression plan', 'Trail map & route planning', 'Priority scheduling'],
    features_es: ['Instructor dedicado + evaluaciones', 'Plan de progresión personalizado', 'Mapa de senderos y planificación de rutas', 'Prioridad en reservaciones'],
    cta_en: 'Get 10 Classes',
    cta_es: 'Contratar Paquete 10',
    highlight: false,
    badge_en: 'SAVE 21%',
    badge_es: 'AHORRO 21%',
  },
  {
    id: 'tour',
    title_en: 'Guided Trail Tour',
    title_es: 'Tour Guiado de Senderos',
    subtitle_en: 'Full-day adventure experience',
    subtitle_es: 'Experiencia de aventura de día completo',
    price_usd: null,
    duration_en: 'Full day / Multi-day available',
    duration_es: 'Día completo / Multi-día disponible',
    features_en: ['Expert local trail guide', 'Curated route for your level', 'Photo & video stops', 'Groups & corporate events'],
    features_es: ['Guía de senderos local experto', 'Ruta curada para tu nivel', 'Paradas para fotos y video', 'Grupos y eventos corporativos'],
    cta_en: 'Request Tour Quote',
    cta_es: 'Cotizar Tour',
    highlight: false,
    badge: null,
  },
];
